# config_cpu.yaml  #used when calling batch training for vertex ai
workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: gcr.io/mlops-tsa/trainmodel-container:latest
        env:
          - name: WANDB_API_KEY
            value: "Placeholder"