wandb_version: 1

batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.00955899514828798
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705064479.774505
    t:
      1:
      - 1
      - 5
      - 50
      - 53
      - 55
      - 105
      2:
      - 1
      - 5
      - 50
      - 53
      - 55
      - 105
      3:
      - 2
      - 23
      - 37
      4: 3.10.13
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
