hydra:
  version_base: 1.3.2  # Specify the Hydra version compatibility
  sweeper:
    _target_: hydra.core.plugins_common.utils.Sweeper
    method: grid
    metric:
      name: loss
      goal: minimize

defaults:
  - override hydra/sweeper: basic
  - override hydra/launcher: ray


parameters:
  learning_rate:
    type: choice
    values: [0.01, 0.001, 0.0001]  # Add more learning rates as needed
  batch_size:
    type: choice
    values: [16, 32, 64]  # Add more batch sizes as needed
  num_epochs:
    type: choice
    values: [5, 10, 15]  # Add more epoch values as needed
