name: "Run tests"

on:
  pull_request:
    branches: [ master, main, dev, data ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: [ubuntu-latest] #windows-latest,mac-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v
